framework/urls.py
from django.conf.urls import patterns, url, include

from framework import views

urlpatterns = patterns('',
	url(r'^$', views.IndexView.as_view(), name='index'),	
    url(r'^artist/(?P<pk>\w+)/$', views.MusicianView.as_view(), name='musician'),    
    url(r'^reviewer/(?P<pk>\w+)/$', views.ReviewerView.as_view(), name='reviewer'),
    url(r'^review/(?P<pk>\w+)/$', views.ReviewView.as_view(), name='review'),
    url(r'^music/(?P<pk>\w+)/$', views.MusicView.as_view(), name='music'),

    url(r'^create/artist/$', views.CreateMusicianView.as_view(), name='createmusician'),
    url(r'^create/reviewer/$', views.CreateReviewerView.as_view(), name='createreviewer'),
    url(r'^add/music/$', views.CreateMusicView.as_view(), name='createmusic'),
    url(r'^add/review/$', views.CreateReviewView.as_view(), name='createreview'),

    url(r'^create/artist/thanks/$', views.ThanksView.as_view(), name='thanksmusician'),
    url(r'^create/reviewer/thanks/$', views.ThanksView.as_view(), name='thanksreviewer'),
    url(r'^add/music/thanks/$', views.ThanksView.as_view(), name='thanksmusic'),
    url(r'^add/review/thanks/$', views.ThanksView.as_view(), name='thanksreview'),    

    url(r'^artists/$', views.ListMusicianView.as_view(), name='listmusician'),
    url(r'^reviewers/$', views.ListReviewerView.as_view(), name='listreviewer'),
    url(r'^reviews/$', views.ListReviewView.as_view(), name='listreview'),
    url(r'^music/$', views.ListMusicView.as_view(), name='listmusic'),

)

mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^base/', include('framework.urls', namespace="base")),
    url(r'^polls/', include('framework.polls_urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
    (r'^accounts/', include('allauth.urls')),    
)

framework/models.py
from django.utils import timezone
from django.db import models
import datetime
from cloudinary.models import CloudinaryField
from django.contrib.auth.models import User


class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')    

    def __unicode__(self): 
        return self.question    

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __unicode__(self): 
        return self.choice_text

class AbstractUser(models.Model):
    class Meta:
        abstract = True
    user = models.ForeignKey(User)        
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)  
    birth_date = models.DateField()        
    description = models.TextField(blank=True)
    website = models.URLField(blank=True)
    email = models.EmailField() # unique=True
    # bank account
    created = models.DateTimeField('Date account created', auto_now_add=True)    
    profile_picture = CloudinaryField('image', blank=True, null=True)
    def __unicode__(self):
        return u'%s %s' % (self.first_name, self.last_name)
    

class Musician(AbstractUser):
    number_reviews_received = models.PositiveSmallIntegerField(blank=True, null=True)
    number_products = models.PositiveSmallIntegerField(blank=True, null=True)
    artist_name = models.CharField(max_length=50, blank=True)

class Reviewer(AbstractUser):
    number_reviews_performed = models.PositiveSmallIntegerField(blank=True, null=True)
    job_title = models.CharField(max_length=50, blank=True)

class Music(models.Model):
    PRODUCT_TYPES = (('S', 'Song'), 
                     ('A', 'Album'),
                     ('C', 'Collection'))
    musician = models.ForeignKey(Musician)    
    product_type = models.CharField(max_length=1, choices=PRODUCT_TYPES)
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    created = models.DateTimeField('Date product created', auto_now_add=True)
    product_picture = CloudinaryField('image', blank=True, null=True)
    average_score = models.PositiveSmallIntegerField(blank=True, null=True)
    number_reviews_received = models.PositiveSmallIntegerField(blank=True, null=True)
    def __unicode__(self):
        return u'%s - %s' % (self.musician, self.title)
    
class Review(models.Model):
    musician = models.ForeignKey(Musician)
    reviewer = models.ForeignKey(Reviewer)        
    product = models.ForeignKey(Music)
    title = models.CharField(max_length=100)
    body = models.TextField(blank=True)
    created = models.DateTimeField('Date review created', auto_now_add=True)
    score = models.PositiveSmallIntegerField()
    def __unicode__(self):
        return u'%s: %s' % (self.reviewer, self.product)

framework/forms.py
from django.forms import ModelForm
from framework.models import Musician, Reviewer


class MusicianForm(ModelForm):
    class Meta:
        model = Musician
        fields = ['first_name', 'last_name', 'birth_date', 'artist_name', 
                  'description', 'website', 'profile_picture']

class ReviewerForm(ModelForm):
    class Meta:
        model = Reviewer
        fields = ['first_name', 'last_name', 'birth_date', 'job_title', 
                  'description', 'website', 'profile_picture']

framework/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from framework.models import Choice, Poll, Musician, Review, Reviewer, Music 
from framework.forms import MusicianForm, ReviewerForm

class IndexView2(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_poll_list'

    def get_queryset(self):
        """Return the last five published polls."""
        return Poll.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Poll
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Poll
    template_name = 'polls/results.html'

def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the poll voting form.
        return render(request, 'polls/detail.html', {
            'poll': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))    

class IndexView(generic.base.TemplateView):
    template_name = 'base/index.html'    
    
class MusicianView(generic.DetailView):
    model = Musician    
    template_name = 'base/musician.html'     

class MusicView(generic.DetailView):
    model = Music
    template_name = 'base/music.html'           

class ReviewerView(generic.DetailView):
    model = Reviewer
    template_name = 'base/reviewer.html'            

class ReviewView(generic.DetailView):
    model = Review
    template_name = 'base/review.html'

# Create

class CreateMusicianView(generic.edit.CreateView):    
    form_class = MusicianForm
    template_name = 'base/create/createmusician.html'    
    success_url = 'thanks/'
    def post(self, request):
        form = self.form_class(request.POST, request.FILES)        
        form = form.save(commit=False)
        form.email = request.user.email
        form.user = request.user
        form.save()
        return HttpResponseRedirect(self.success_url)

class CreateReviewerView(generic.edit.CreateView):
    form_class = ReviewerForm
    template_name = 'base/create/createreviewer.html'   
    success_url = 'thanks/'
    def post(self, request):
        form = self.form_class(request.POST, request.FILES)        
        form = form.save(commit=False)
        form.user = request.user
        form.email = request.user.email
        form.save()
        return HttpResponseRedirect(self.success_url)

class CreateMusicView(generic.edit.CreateView):
    model = Music
    template_name = 'base/create/createmusic.html'
    fields = ['musician', 'product_type', 'title', 'description', 'product_picture']
    success_url = 'thanks/'
    # musician should be auto-populated

class CreateReviewView(generic.edit.CreateView):
    model = Review
    template_name = 'base/create/createreview.html'
    fields = ['musician', 'reviewer', 'product', 'title', 'body', 'score']
    success_url = 'thanks/'
    # reviewer should be auto-populated

# Lists

class ListMusicianView(generic.ListView):
    template_name = 'base/lists/listmusician.html'
    context_object_name = 'musician_list'
    def get_queryset(self):        
        return Musician.objects.order_by('-created')

class ListReviewerView(generic.ListView):
    template_name = 'base/lists/listreviewer.html'
    context_object_name = 'reviewer_list'
    def get_queryset(self):        
        return Reviewer.objects.order_by('-created')

class ListReviewView(generic.ListView):
    template_name = 'base/lists/listreview.html'
    context_object_name = 'review_list'
    def get_queryset(self):        
        return Review.objects.order_by('-created')

class ListMusicView(generic.ListView):
    template_name = 'base/lists/listmusic.html'
    context_object_name = 'music_list'
    def get_queryset(self):        
        return Music.objects.order_by('-created')

# Thanks

class ThanksView(generic.base.TemplateView):    
    template_name = 'base/thanks.html'

framework/templates/base/index.html
<br><br>

{% if not request.user.is_authenticated %}
You need to <a href="{% url 'account_login' %}">login</a> to add content<br><br>
{% else %} 
Hi {{ request.user.username }}! Click <a href="{% url 'account_logout' %}">here</a> to logout<br><br>
{% endif %}
<br><br>

<a href="{% url 'base:index' %}">Home</a><br><br>
<a href="{% url 'base:listmusician' %}">Artists</a><br><br>
<a href="{% url 'base:listreviewer' %}">Reviewers</a><br><br>
<a href="{% url 'base:listmusic' %}">Music</a><br><br>
<a href="{% url 'base:listreview' %}">Reviews</a><br><br>
<br><br>

{% if request.user.is_authenticated %}
<a href="{% url 'base:createmusician' %}">Register Artist</a><br><br>
<a href="{% url 'base:createreviewer' %}">Register Reviewer</a><br><br>
<a href="{% url 'base:createmusic' %}">Add Music</a><br><br>
<a href="{% url 'base:createreview' %}">Add Review</a><br><br>
{% endif %}

framework/templates/base/music.html
Check out the following amazing song!

{{music.object}}
<br><br>
<p>{{ music.musician }}</p>
<p>{{ music.title }}</p>
<p>{{ music.product_type }}</p>

<br><br>
<a href="{% url 'base:listmusic' %}">Return to music list</a><br><br>

framework/templates/base/musician.html
{% load cloudinary %}

Welcome Artist!
<br><br>
<p>{{ musician.first_name }}</p>
<p>{{ musician.last_name }}</p>
<p>{{ musician.created }}</p>
<p>{{ musician.email }}</p>
<p>{{ musician.birth_date }}</p>
<p>{{ musician.description }}</p>
<p>{{ musician.website }}</p>

{% cloudinary musician.profile_picture width=100 height=150 crop="fill" %}

<br><br>
<a href="{% url 'base:listmusician' %}">Return to artist list</a><br><br>

framework/templates/base/musicianproduct.html
{{musicianproduct.object}}
<br><br>
<p>{{ musicianproduct.musician }}</p>
<p>{{ musicianproduct.title }}</p>
<p>{{ musicianproduct.product_type }}</p>

framework/templates/base/review.html
Please read the review of {{review.reviewer}} on
<br><br>
<p>{{ review.title }}</p>
<p>{{ review.body }}</p>
<p>{{ review.release_date }}</p>
<p>{{ review.num_stars }}</p>

<br><br>
<a href="{% url 'base:listreview' %}">Return to review list</a><br><br>

framework/templates/base/reviewer.html
{% load cloudinary %}

Welcome Reviewer!
<br><br>
<p>{{ reviewer.first_name }}</p>
<p>{{ reviewer.last_name }}</p>
<p>{{ reviewer.created }}</p>
<p>{{ reviewer.email }}</p>
<p>{{ reviewer.birth_date }}</p>

{% cloudinary reviewer.profile_picture width=100 height=150 crop="fill" %}

<br><br>
<a href="{% url 'base:listreviewer' %}">Return to reviewer list</a><br><br>

framework/templates/base/thanks.html
Thanks!
<br><br>
<a href="{% url 'base:index' %}">Go to Index</a>